"use client"

import React, { useState } from "react"
import { motion } from "framer-motion"
import { Linkedin, Globe, Copy, Check } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"

interface SocialGeneratorsProps {
  careerTitle: string
  userName: string
  mission: string
  highlights: string[]
}

export function SocialGenerators({ careerTitle, userName, mission, highlights }: SocialGeneratorsProps) {
  const [copied, setCopied] = useState(false)

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const linkedinBio = `🚀 Future ${careerTitle} | ${mission}\n\nFocused on bridging the gap between human creativity and AI-native workflows. \n\nKey Focus Areas:\n${highlights.map(h => `• ${h}`).join('\n')}\n\nGenerated by Daedalus_OS`

  const portfolioHeadline = `${userName} // AI-Native ${careerTitle}`

  return (
    <Card className="border-primary/10">
      <CardHeader>
        <CardTitle className="text-lg flex items-center gap-2">
          <Globe className="w-5 h-5 text-primary" />
          Identity Projection Lab
        </CardTitle>
        <CardDescription>Generate professional artifacts for your future self.</CardDescription>
      </CardHeader>
      <CardContent>
        <Tabs defaultValue="linkedin">
          <TabsList className="grid w-full grid-cols-2 bg-muted/50">
            <TabsTrigger value="linkedin" className="gap-2">
              <Linkedin className="w-3.5 h-3.5" /> LinkedIn
            </TabsTrigger>
            <TabsTrigger value="portfolio" className="gap-2">
              <Globe className="w-3.5 h-3.5" /> Portfolio
            </TabsTrigger>
          </TabsList>

          <TabsContent value="linkedin" className="pt-4 space-y-4">
            <div className="p-4 rounded-lg bg-black/[0.02] border font-mono text-[11px] whitespace-pre-wrap leading-relaxed">
              {linkedinBio}
            </div>
            <Button
              variant="outline"
              className="w-full gap-2"
              onClick={() => copyToClipboard(linkedinBio)}
            >
              {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
              {copied ? "Copied Bio" : "Copy LinkedIn Bio"}
            </Button>
          </TabsContent>

          <TabsContent value="portfolio" className="pt-4 space-y-4">
            <div className="space-y-4">
              <div className="p-4 rounded-lg border bg-gradient-to-br from-primary/5 to-transparent">
                <p className="text-[10px] font-bold text-primary uppercase mb-1">Landing Headline</p>
                <p className="text-lg font-black tracking-tight">{portfolioHeadline}</p>
              </div>
              <Button
                variant="outline"
                className="w-full gap-2"
                onClick={() => copyToClipboard(portfolioHeadline)}
              >
                {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
                Copy Headline
              </Button>
            </div>
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  )
}
